version: "3"
services:
  mongo:
    image: "mongo:3-stretch"
    container_name: "mongo"
    ports:
      - "27017:27017"
  mongo-express:
    image: "mongo-express:latest"
    container_name: "mongoex"
    ports:
      - "8081:8081"
    links:
     - mongo
  # objectreport:
  #   build: ./project
  #   container_name: objectreport
  #   ports:
  #     - "8000:8080"
  #   links:
  #     - mongo:mongo
  #   depends_on:
  #     - mongo
